user nginx;
worker_processes auto;

pid /var/run/nginx.pid;

events {
    use epoll;
    worker_connections 51200;
    multi_accept on;
}
stream {
    map $ssl_preread_server_name $backend_name {
        www.apple.com xray;
    }
    upstream xray {
        server 192.168.1.70:20000;
    }

    server {
        listen 443 reuseport;
        listen [::]:443 reuseport;
        proxy_pass $backend_name;
        ssl_preread on;
    }
}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Security Enhancements
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    server_tokens off;

    # Logging
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                '$status $body_bytes_sent "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for" "$host"';
    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log;

    # Optimization
    server_names_hash_bucket_size 512;
    client_header_buffer_size 32k;
    large_client_header_buffers 4 32k;
    client_max_body_size 50m;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 60;
    keepalive_requests 100;

    # FastCGI
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 256k;
    fastcgi_intercept_errors on;

    # Gzip
    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 2;
    gzip_types text/plain application/javascript application/x-javascript text/javascript text/css application/xml;
    gzip_vary on;
    gzip_proxied expired no-cache no-store private auth;
    gzip_disable "MSIE [1-6]\.";

    # Limit connections
    limit_conn_zone $binary_remote_addr zone=perip:10m;
    limit_conn perip 100;
    limit_conn_zone $server_name zone=perserver:10m;
    limit_conn perserver 100;

    include /etc/nginx/conf.d/*.conf;
}